### ISSUE TITLE
Gradient has outdates direction and syntax

### ISSUE THREAD

**Issue by azz0r** [BTplc/CORE#53]
Found the root cause: https://github.com/BTplc/CORE/blob/master/dist/CORE-Sass/core.scss#L209

app:error Warning in ./~/sass-loader?sourceMap!./src/styles/main.scss
autoprefixer: /Users/azz0r/Sites/BT/node_modules/CORE/dist/CORE-Sass/core.scss:209:4: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`. +0ms

**Comment by danciu** [comment]
@azz0r , we have to update the `sass-css3-mixins` package and make a new release :)

**Comment by azz0r** [comment]
Updated in PR #54

**Comment by danciu** [comment]
thanks @azz0r 💯

**Comment by danciu** [comment]
@azz0r you back? 💃

**Comment by azz0r** [comment]
Checking over old (super old) things attached to me on github, theres definitely a few BT repos to clean up 🗡 

🕺🏼
